kind: pipeline
name: ci
steps:
- commands:
  - sudo chown -R makepkg /drone
  - sudo chown -R makepkg /repo
  environment:
    REPODIR: /repo
  image: zachfi/shell:latest
  name: chown
  pull: always
  volumes:
  - name: cache
    path: /repo
  - host:
      path: /var/run/docker.sock
    name: docker.sock
- commands:
  - make modules
  environment:
    REPODIR: /repo
  image: zachfi/shell:latest
  name: submodules
  pull: always
  volumes:
  - name: cache
    path: /repo
  - host:
      path: /var/run/docker.sock
    name: docker.sock
- commands:
  - make repo
  environment:
    REPODIR: /repo
  image: zachfi/shell:latest
  name: repo
  pull: always
  volumes:
  - name: cache
    path: /repo
  - host:
      path: /var/run/docker.sock
    name: docker.sock
- commands:
  - make image
  environment:
    REPODIR: /repo
  image: zachfi/shell:latest
  name: image
  pull: always
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
- commands:
  - make publish
  environment:
    REPODIR: /repo
  image: zachfi/shell:latest
  name: publish
  pull: always
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  when:
    branch:
    - main
trigger:
  event:
  - push
volumes:
- name: cache
  temp: {}
