kind: pipeline
name: ci
steps:
- commands:
  - sudo chown -R makepkg /drone
  - sudo chown -R makepkg /repo
  environment:
    REPODIR: /repo
  image: zachfi/shell:archlinux
  name: chown
  pull: always
  volumes:
  - name: cache
    path: /repo
- commands:
  - make modules
  environment:
    REPODIR: /repo
  image: zachfi/shell:archlinux
  name: submodules
  pull: always
  volumes:
  - name: cache
    path: /repo
- commands:
  - ls -l
  - make repo
  environment:
    REPODIR: /repo
  image: zachfi/shell:archlinux
  name: repo
  pull: always
  volumes:
  - name: cache
    path: /repo
- commands:
  - make image
  environment:
    REPODIR: /repo
  image: zachfi/shell:archlinux
  name: image
  pull: always
  volumes:
  - name: cache
    path: /repo
volumes:
- name: cache
  temp: {}
