---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - sudo mkdir -p /repo/x86_64
  - sudo chown -R makepkg /repo
  - sudo chown -R makepkg /drone
  - git submodule init
  - git submodule update
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: init-repo-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - cd nodemanager-bin
  - makepkg -c
  environment:
    CARCH: x86_64
    OPTIONS: (!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto
      !autodeps)
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: build-pkg-nodemanager-bin-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - cd k3s-bin
  - makepkg -c
  environment:
    CARCH: x86_64
    OPTIONS: (!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto
      !autodeps)
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: build-pkg-k3s-bin-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - cd gomplate-bin
  - makepkg -c
  environment:
    CARCH: x86_64
    OPTIONS: (!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto
      !autodeps)
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: build-pkg-gomplate-bin-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - cd duo_unix
  - makepkg -c
  environment:
    CARCH: x86_64
    OPTIONS: (!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto
      !autodeps)
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: build-pkg-duo_unix-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - cd zen-browser-avx2-bin
  - makepkg -c
  environment:
    CARCH: x86_64
    OPTIONS: (!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto
      !autodeps)
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: build-pkg-zen-browser-avx2-bin-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - cp nodemanager-bin/*x86_64*.pkg.tar.zst /repo/x86_64
  - cp k3s-bin/*x86_64*.pkg.tar.zst /repo/x86_64
  - cp gomplate-bin/*x86_64*.pkg.tar.zst /repo/x86_64
  - cp duo_unix/*x86_64*.pkg.tar.zst /repo/x86_64
  - cp zen-browser-avx2-bin/*x86_64*.pkg.tar.zst /repo/x86_64
  - rm /repo/x86_64/*-debug-*
  - repo-add /repo/x86_64/custom.db.tar.gz /repo/x86_64/*pkg.tar.zst
  environment:
    CARCH: x86_64
    OPTIONS: (!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto
      !autodeps)
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: make-repo-x86_64
  volumes:
  - name: cache
    path: /repo
- commands:
  - sudo docker build -t reg.dist.svc.cluster.znet:5000/zachfi/aur -f Dockerfile /repo
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: build-image
  volumes:
  - name: cache
    path: /repo
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - sudo docker push reg.dist.svc.cluster.znet:5000/zachfi/aur
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  name: publish-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    branch:
    - main
trigger:
  branch:
  - main
  event:
  - push
volumes:
- name: cache
  temp: {}
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: b0f758b87f468ce9e2a8e46bdcd11e233b0af78b266db38d773539ecad01059c

...
