kind: pipeline
name: ci
steps:
- commands:
  - whoami
  - pwd
  - ls -ld
  - ls -l
  - make repo
  image: zachfi/shell:archlinux
  name: repo
  pull: always
- commands:
  - make imar
  image: zachfi/shell:archlinux
  name: image
  pull: always
